-- Insert beer types
INSERT INTO beer_types (id, name) VALUES (nextval('beer_types_seq'), 'IPA');
INSERT INTO beer_types (id, name) VALUES (nextval('beer_types_seq'), 'Stout');
INSERT INTO beer_types (id, name) VALUES (nextval('beer_types_seq'), 'Lager');
INSERT INTO beer_types (id, name) VALUES (nextval('beer_types_seq'), 'Wheat Beer');
INSERT INTO beer_types (id, name) VALUES (nextval('beer_types_seq'), 'Pale Ale');
INSERT INTO beer_types (id, name) VALUES (nextval('beer_types_seq'), 'Amber Ale');
INSERT INTO beer_types (id, name) VALUES (nextval('beer_types_seq'), 'Pilsner');
INSERT INTO beer_types (id, name) VALUES (nextval('beer_types_seq'), 'Blonde Ale');
INSERT INTO beer_types (id, name) VALUES (nextval('beer_types_seq'), 'Porter');
INSERT INTO beer_types (id, name) VALUES (nextval('beer_types_seq'), 'Double IPA');
INSERT INTO beer_types (id, name) VALUES (nextval('beer_types_seq'), 'Milk Stout');
INSERT INTO beer_types (id, name) VALUES (nextval('beer_types_seq'), 'Sour Ale');
INSERT INTO beer_types (id, name) VALUES (nextval('beer_types_seq'), 'Bock');
INSERT INTO beer_types (id, name) VALUES (nextval('beer_types_seq'), 'Tripel');
INSERT INTO beer_types (id, name) VALUES (nextval('beer_types_seq'), 'Fruit Beer');
INSERT INTO beer_types (id, name) VALUES (nextval('beer_types_seq'), 'Hefeweizen');
INSERT INTO beer_types (id, name) VALUES (nextval('beer_types_seq'), 'Saison');
INSERT INTO beer_types (id, name) VALUES (nextval('beer_types_seq'), 'Belgian Dubbel');
INSERT INTO beer_types (id, name) VALUES (nextval('beer_types_seq'), 'Barleywine');
INSERT INTO beer_types (id, name) VALUES (nextval('beer_types_seq'), 'Gose');

INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Sierra Nevada Pale Ale', (SELECT id FROM beer_types WHERE name = 'Pale Ale'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Guinness Draught', (SELECT id FROM beer_types WHERE name = 'Stout'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Samuel Adams Boston Lager', (SELECT id FROM beer_types WHERE name = 'Lager'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Blue Moon Belgian White', (SELECT id FROM beer_types WHERE name = 'Wheat Beer'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Stone IPA', (SELECT id FROM beer_types WHERE name = 'IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Budweiser', (SELECT id FROM beer_types WHERE name = 'Lager'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Heineken', (SELECT id FROM beer_types WHERE name = 'Lager'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Corona Extra', (SELECT id FROM beer_types WHERE name = 'Lager'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Pabst Blue Ribbon', (SELECT id FROM beer_types WHERE name = 'Lager'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'New Belgium Fat Tire', (SELECT id FROM beer_types WHERE name = 'Amber Ale'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Dogfish Head 90 Minute IPA', (SELECT id FROM beer_types WHERE name = 'Double IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Founders All Day IPA', (SELECT id FROM beer_types WHERE name = 'IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Bell’s Two Hearted Ale', (SELECT id FROM beer_types WHERE name = 'IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Russian River Pliny the Elder', (SELECT id FROM beer_types WHERE name = 'Double IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Lagunitas IPA', (SELECT id FROM beer_types WHERE name = 'IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Miller Lite', (SELECT id FROM beer_types WHERE name = 'Lager'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Coors Light', (SELECT id FROM beer_types WHERE name = 'Lager'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Dos Equis Lager Especial', (SELECT id FROM beer_types WHERE name = 'Lager'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Stella Artois', (SELECT id FROM beer_types WHERE name = 'Lager'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Sapporo Premium Lager', (SELECT id FROM beer_types WHERE name = 'Lager'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Brooklyn Lager', (SELECT id FROM beer_types WHERE name = 'Lager'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Firestone Walker 805', (SELECT id FROM beer_types WHERE name = 'Blonde Ale'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Goose Island Bourbon County Stout', (SELECT id FROM beer_types WHERE name = 'Stout'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Deschutes Black Butte Porter', (SELECT id FROM beer_types WHERE name = 'Porter'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Pilsner Urquell', (SELECT id FROM beer_types WHERE name = 'Pilsner'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Weihenstephaner Hefeweissbier', (SELECT id FROM beer_types WHERE name = 'Hefeweizen'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Guinness Foreign Extra Stout', (SELECT id FROM beer_types WHERE name = 'Stout'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Yuengling Traditional Lager', (SELECT id FROM beer_types WHERE name = 'Lager'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Sculpin IPA', (SELECT id FROM beer_types WHERE name = 'IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Sierra Nevada Torpedo Extra IPA', (SELECT id FROM beer_types WHERE name = 'IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Modelo Especial', (SELECT id FROM beer_types WHERE name = 'Lager'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Narragansett Lager', (SELECT id FROM beer_types WHERE name = 'Lager'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Abita Purple Haze', (SELECT id FROM beer_types WHERE name = 'Fruit Beer'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Shiner Bock', (SELECT id FROM beer_types WHERE name = 'Bock'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Avery Brewing White Rascal', (SELECT id FROM beer_types WHERE name = 'Wheat Beer'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Fat Head’s Head Hunter IPA', (SELECT id FROM beer_types WHERE name = 'IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Great Lakes Edmund Fitzgerald Porter', (SELECT id FROM beer_types WHERE name = 'Porter'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'North Coast Old Rasputin Russian Imperial Stout', (SELECT id FROM beer_types WHERE name = 'Stout'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Boulevard Tank 7 Farmhouse Ale', (SELECT id FROM beer_types WHERE name = 'Saison'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Breckenridge Brewery Vanilla Porter', (SELECT id FROM beer_types WHERE name = 'Porter'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Leinenkugel’s Summer Shandy', (SELECT id FROM beer_types WHERE name = 'Fruit Beer'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Troegs Nugget Nectar', (SELECT id FROM beer_types WHERE name = 'Amber Ale'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Cigar City Jai Alai IPA', (SELECT id FROM beer_types WHERE name = 'IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Allagash White', (SELECT id FROM beer_types WHERE name = 'Wheat Beer'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Dogfish Head 60 Minute IPA', (SELECT id FROM beer_types WHERE name = 'IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Left Hand Milk Stout Nitro', (SELECT id FROM beer_types WHERE name = 'Milk Stout'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Founders Breakfast Stout', (SELECT id FROM beer_types WHERE name = 'Stout'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Oskar Blues Dale’s Pale Ale', (SELECT id FROM beer_types WHERE name = 'Pale Ale'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Ballast Point Grapefruit Sculpin', (SELECT id FROM beer_types WHERE name = 'IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Red Stripe', (SELECT id FROM beer_types WHERE name = 'Lager'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Boddingtons Pub Ale', (SELECT id FROM beer_types WHERE name = 'Bitter'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Anchor Steam Beer', (SELECT id FROM beer_types WHERE name = 'California Common'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Kona Big Wave Golden Ale', (SELECT id FROM beer_types WHERE name = 'Golden Ale'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Pilsner Kelheim Hopfenstopfer Comet', (SELECT id FROM beer_types WHERE name = 'Pilsner'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Ommegang Hennepin', (SELECT id FROM beer_types WHERE name = 'Saison'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Bear Republic Racer 5 IPA', (SELECT id FROM beer_types WHERE name = 'IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Harpoon IPA', (SELECT id FROM beer_types WHERE name = 'IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'New Belgium Voodoo Ranger IPA', (SELECT id FROM beer_types WHERE name = 'IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Abita Amber', (SELECT id FROM beer_types WHERE name = 'Amber Ale'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Harpoon UFO White', (SELECT id FROM beer_types WHERE name = 'Wheat Beer'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Sierra Nevada Kellerweis', (SELECT id FROM beer_types WHERE name = 'Hefeweizen'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Deschutes Mirror Pond Pale Ale', (SELECT id FROM beer_types WHERE name = 'Pale Ale'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Boulevard Unfiltered Wheat Beer', (SELECT id FROM beer_types WHERE name = 'Wheat Beer'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Sierra Nevada Hazy Little Thing IPA', (SELECT id FROM beer_types WHERE name = 'IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Alaskan Amber', (SELECT id FROM beer_types WHERE name = 'Amber Ale'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'New Belgium Citradelic Tangerine IPA', (SELECT id FROM beer_types WHERE name = 'IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Victory Golden Monkey', (SELECT id FROM beer_types WHERE name = 'Tripel'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Shiner Ruby Redbird', (SELECT id FROM beer_types WHERE name = 'Fruit Beer'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Left Hand Nitro Milk Stout', (SELECT id FROM beer_types WHERE name = 'Milk Stout'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Sixpoint Resin', (SELECT id FROM beer_types WHERE name = 'Double IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Great Lakes Dortmunder Gold', (SELECT id FROM beer_types WHERE name = 'Lager'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'New Belgium Ranger IPA', (SELECT id FROM beer_types WHERE name = 'IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'SweetWater 420 Extra Pale Ale', (SELECT id FROM beer_types WHERE name = 'Pale Ale'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Firestone Walker Double Jack', (SELECT id FROM beer_types WHERE name = 'Double IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'New Belgium La Folie', (SELECT id FROM beer_types WHERE name = 'Sour Ale'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), '3 Floyds Zombie Dust', (SELECT id FROM beer_types WHERE name = 'Pale Ale'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Boulevard The Sixth Glass', (SELECT id FROM beer_types WHERE name = 'Quadrupel'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Bear Republic Hop Rod Rye', (SELECT id FROM beer_types WHERE name = 'Rye IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Avery Brewing Maharaja', (SELECT id FROM beer_types WHERE name = 'Double IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Anchor Porter', (SELECT id FROM beer_types WHERE name = 'Porter'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Founders Porter', (SELECT id FROM beer_types WHERE name = 'Porter'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Three Floyds Alpha King', (SELECT id FROM beer_types WHERE name = 'Pale Ale'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Stone Delicious IPA', (SELECT id FROM beer_types WHERE name = 'IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Abita Turbodog', (SELECT id FROM beer_types WHERE name = 'Brown Ale'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'North Coast Scrimshaw Pilsner', (SELECT id FROM beer_types WHERE name = 'Pilsner'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Deschutes Fresh Squeezed IPA', (SELECT id FROM beer_types WHERE name = 'IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Victory Prima Pils', (SELECT id FROM beer_types WHERE name = 'Pilsner'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Samuel Smith Oatmeal Stout', (SELECT id FROM beer_types WHERE name = 'Oatmeal Stout'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Stone Tangerine Express IPA', (SELECT id FROM beer_types WHERE name = 'IPA'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), 'Lagunitas Little Sumpin’ Sumpin’ Ale', (SELECT id FROM beer_types WHERE name = 'Wheat Ale'));
INSERT INTO beers (id, name, type_id) VALUES (nextval('beers_seq'), '21st Amendment Hell or High Watermelon Wheat', (SELECT id FROM beer_types WHERE name = 'Wheat Beer'));